install: lib lib/cssreset-min.css lib/jquery.min.js lib/bootstrap.min.js lib/bootstrap.min.css

# These could be curled down later. I'm just linking to the ones we already have in the server

lib:
	mkdir lib

lib/cssreset-min.css:
	ln -s ../../server/externals/static/cssreset-min.css lib/cssreset-min.css

lib/jquery.min.js:
	ln -s ../../server/externals/static/jquery.min.js lib/jquery.min.js

lib/bootstrap.min.js:
	ln -s ../../server/externals/static/js/bootstrap.min.js lib/bootstrap.min.js

lib/bootstrap.min.css:
	ln -s ../../server/externals/static/css/bootstrap.min.css lib/bootstrap.min.css
