install: cssreset-min.css jquery.min.js bootstrap.min.js bootstrap.min.css

cssreset-min.css:
	ln -s ../server/externals/static/cssreset-min.css cssreset-min.css

jquery.min.js:
	ln -s ../server/externals/static/jquery.min.js jquery.min.js

bootstrap.min.js:
	ln -s ../server/externals/static/js/bootstrap.min.js bootstrap.min.js

bootstrap.min.css:
	ln -s ../server/externals/static/css/bootstrap.min.css bootstrap.min.css
